
spring:
  application:
    name: flywayapp
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/xyz?autoreconnect=true"
    password: "Khalid098@"
    username: "root"
flyway:
  url: jdbc:mysql://localhost:3306/mysql
  schemas: xyz
  user: "root"
  password: "Khalid098@"